set_property SRC_FILE_INFO {cfile:/sim/freq-test/ddr3-pack/ddr3-sume/ddr3-sume.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc rfile:../../../ddr3-sume.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc id:1 order:EARLY scoped_inst:u_mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:/sim/freq-test/ddr3-pack/ddr3_tb/SUME_Master.xdc rfile:../../../../ddr3_tb/SUME_Master.xdc id:2} [current_design]
current_instance u_mig_7series_0
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12 [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B27 [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23 [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C25 [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E24 [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D22 [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A29 [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A30 [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A32 [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D28 [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C28 [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C29 [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D27 [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C31 [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D30 [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E30 [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C30 [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F30 [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F27 [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F26 [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F29 [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E29 [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {ddr3_addr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B23 [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A31 [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F31 [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_p}]
set_property src_info {type:SCOPED_XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports {sys_clk_p}]
set_property src_info {type:SCOPED_XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E34 [get_ports {sys_clk_p}]
set_property src_info {type:SCOPED_XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_n}]
set_property src_info {type:SCOPED_XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports {sys_clk_n}]
set_property src_info {type:SCOPED_XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E35 [get_ports {sys_clk_n}]
set_property src_info {type:SCOPED_XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:690 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A26 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:708 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:714 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:720 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B28 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:728 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E27 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y35 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y34 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y33 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y32 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:779 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y35 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y34 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y33 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y32 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:796 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:799 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:802 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:803 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:804 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:805 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:806 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:807 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:808 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:809 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:812 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:813 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:814 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:817 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:819 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y393 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:823 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y381 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:824 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y369 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:825 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y357 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:826 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y493 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:827 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y481 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:828 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y469 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:829 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y457 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:833 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:834 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:842 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start
set_property src_info {type:SCOPED_XDC file:1 line:846 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:1 line:850 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
current_instance
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVDS     } [get_ports { FPGA_SYSCLK_N }]; #IO_L13N_T2_MRCC_38 Sch=fpga_sysclk_n
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H19   IOSTANDARD LVDS     } [get_ports { FPGA_SYSCLK_P }]; #IO_L13P_T2_MRCC_38 Sch=fpga_sysclk_p
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AR22  IOSTANDARD LVCMOS15 } [get_ports { init_calib_complete }]; #IO_L11N_T1_SRCC_33 Sch=led[0]
